-
  version: 1.4.1-{build}
  configuration:
  - FsTest

  image:
    - Visual Studio 2019
    - Visual Studio 2017
    - Visual Studio 2015

  install:
    - ps: |
        Write-Host "Before reboot"
        Start-Sleep -s 2
        Restart-Computer
        Start-Sleep -s 240 # will reboot before this is finished and proceed with next build step
        Write-Host "Did not reboot for some reason, trying Restart-Computer -Force"
        Start-Sleep -s 2
        Restart-Computer -Force
        Start-Sleep -s 240
        Write-Host "Still has not rebooted"
        throw ("Tried rebooting two times, failed")

  build_script:
  - ps: |
      Write-Host We have reboot!
